### ISSUE TITLE
Checking a monster with an index of 4 or higher will crash when selecting fight

### ISSUE THREAD

**Issue by Veblettor** [Crazys-JS/BugTale-Standalone#3]
How to repeat:
1.Add 4 or more enemies to the battle.
2.Use Spy or Changelog on an enemy that is 4th or higher on the list.
3.Open the FIGHT Menu. This will cause the game to crash.

This seems to happen because the game tries to spawn a mercy bar for a 4th enemy name when it doesn't exist yet. The 3rd enemy's mercy bar also glitches out when you have 4+ monsters.
![image](https://user-images.githubusercontent.com/51139141/236189543-51785f57-5079-41e6-8a7e-241de8b6b7cf.png)
![image](https://user-images.githubusercontent.com/51139141/236189680-96cd4b90-b2c0-40a0-9a0e-a14e0f31a188.png)

**Comment by Crazys-JS** [comment]
Seems to be caused simply because of the fact that there is no events to listen to for UI updates on FIGHT menu. New behavior in bugtale-mp library:

If enemy count is below 3, keep current behavior.
If enemy count is higher than or equal to 3, hide all mercy bars in FIGHT menu.

https://github.com/Crazys-JS/BugTale-Standalone/commit/59a662dfc634f77b272286c591676f7d6fd4755d
